version: '3.9'
services:
  backend:
    container_name: app_backend
    build: ./my-hobby-list-backend
    ports:
      - 3001:8080
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=3002

  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_app
    restart: 'always'
