version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./my-hobby-list-frontend
    ports:
      - 4200:80
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend
      - db
    volumes: 
      - ./my-hobby-list-frontend/src:/app-frontend/src

  backend:
    container_name: app_backend
    build: ./my-hobby-list-backend
    ports:
      - 3001:8080
    platform: linux/x86_64
    restart: "on-failure"
    working_dir: /app-backend
    depends_on:
      - db
    volumes: 
      - ./my-hobby-list-backend/src:/app-backend/src
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=3306
      - JWT_SECRET=W2XFmnJht6IlH0xfNqjvUjqYnSDgbj3basIDSNTvxZRNDj20G4QhECx4YxWwotJFdMJq6MbQSrlMxvrr47p4+InmHRnWtVUBi/GrZR5N+num0JpfCDLQBSohgYCKi7U8dbUQOmW3r7+03RW41eMMGsfXcwob8ahOHbyPuRijGo71mhVcLR320t9kjeLgSY03D970SaKCdeBtE6wAtrxvzH0DQJIUPfTMrdBu/Z6COYVvHkyMsF/AlORNKfdJP5hUMTDqHngnSPJ2nTr394M7DH6gtILxGP6qU6j6V0Rkc6naahSVnYS2VewvGF9/Pu/hR6JM/qPhWUiKBdV/ZZWMuA==

  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_app
    restart: 'always'
