# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:
  push:
    paths:
      - 'my-hobby-list-frontend/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'my-hobby-list-frontend/**'
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      working-directory: ./my-hobby-list-frontend
      run: npm ci
    - name: Lint
      working-directory: ./my-hobby-list-frontend
      run: npm run lint
    - name: Tests
      working-directory: ./my-hobby-list-frontend
      run: npm test -- --watch=false --browsers=ChromeHeadless
    - name: Build
      working-directory: ./my-hobby-list-frontend
      run: npm run build
